# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MinecraftServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='mcserver',
            name='IPaddress',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='mcserver',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
